#
# GNUmakefile - Generated by ProjectCenter
#
ifeq ($(GNUSTEP_MAKEFILES),)
 GNUSTEP_MAKEFILES := $(shell gnustep-config --variable=GNUSTEP_MAKEFILES 2>/dev/null)
endif
ifeq ($(GNUSTEP_MAKEFILES),)
 $(error You need to set GNUSTEP_MAKEFILES before compiling!)
endif

include $(GNUSTEP_MAKEFILES)/common.make

#
# Framework
#
VERSION = 0.1
PACKAGE_NAME = SystemConfiguration
FRAMEWORK_NAME = SystemConfiguration
SystemConfiguration_CURRENT_VERSION_NAME = 0.1
SystemConfiguration_DEPLOY_WITH_CURRENT_VERSION = yes


#
# Public headers (will be installed)
#
SystemConfiguration_HEADER_FILES = \
SystemConfiguration.h \
CaptiveNetwork.h 

#
# Objective-C Class files
#
SystemConfiguration_OBJC_FILES = \
CaptiveNetwork.m

#
# Makefiles
#
-include GNUmakefile.preamble
include $(GNUSTEP_MAKEFILES)/aggregate.make
include $(GNUSTEP_MAKEFILES)/framework.make
-include GNUmakefile.postamble
